version: "3.7"

services:

  ccg-api:
    container_name: ccg-api
    image: ccg-api
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - docker-compose-local.env
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
    volumes:
      - ./configuration:/home/gola/configuration
      - data-volume:/data-volume
    command: ["/bin/sh" , "-c", "sleep 5 && /home/gola/ccg-api"]
    networks:
      - gola-network


volumes:
  data-volume:

networks:
  gola-network:
    external: true
