apiVersion: v1
kind: Secret
metadata:
  annotations:
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  name: {{ include "gola-api.name" . }}-secret
type: Opaque
stringData:
  SMTP_CLIENT_PASSWORD: "{{ .Values.client.password }}"
