version: '3.7'
services:

  build-env:
    image: golang:1.18.8-alpine3.16
    environment:
      - GO111MODULE=on
      - GOSUMDB=off
      - GOPRIVATE=github.com/inclusi-blog
    volumes:
      - type: volume
        source: ccg_dep
        target: /go
      - type: bind
        source: ../
        target: /home/gola/ccg-api
    working_dir: /home/gola/ccg-api
volumes:
  ccg_dep:
