// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ccg/v1/email/send": {
            "post": {
                "description": "API to send email,\nIf IncludeBaseTemplate is true then, header/footer (logos + disclaimer) is included",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Email"
                ],
                "summary": "API to send email",
                "parameters": [
                    {
                        "description": "Email Request",
                        "name": "emailRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http_request_response.EmailRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {},
                    "400": {
                        "description": "If From/To/Subject/Body are empty",
                        "schema": {
                            "$ref": "#/definitions/golaerror.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/golaerror.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "golaerror.Error": {
            "type": "object",
            "properties": {
                "additionalData": {
                    "type": "additionalData"
                },
                "errorCode": {
                    "type": "string"
                },
                "errorMessage": {
                    "type": "string"
                }
            }
        },
        "http_request_response.Attachment": {
            "type": "object",
            "required": [
                "base64_encoded_data",
                "file_name"
            ],
            "properties": {
                "base64_encoded_data": {
                    "type": "string",
                    "example": "base64 encoded value"
                },
                "file_name": {
                    "type": "string",
                    "example": "fileName.pdf"
                }
            }
        },
        "http_request_response.EmailRequest": {
            "type": "object",
            "required": [
                "from",
                "message_body",
                "subject",
                "to"
            ],
            "properties": {
                "attachments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http_request_response.Attachment"
                    }
                },
                "from": {
                    "type": "string",
                    "example": "abc@gola.xyz"
                },
                "include_base_template": {
                    "type": "boolean",
                    "example": true
                },
                "message_body": {
                    "type": "object",
                    "$ref": "#/definitions/http_request_response.MessageBody"
                },
                "subject": {
                    "type": "string",
                    "example": "base64 encoded value"
                },
                "to": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "abc@gmail.com"
                    ]
                }
            }
        },
        "http_request_response.MessageBody": {
            "type": "object",
            "required": [
                "base64_encoded_content"
            ],
            "properties": {
                "base64_encoded_content": {
                    "type": "string",
                    "example": "base64 encoded value"
                },
                "mime_type": {
                    "description": "Use text/plain as default",
                    "type": "string",
                    "example": "text/html"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
